// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/blockchain_api/blockchain.proto

// Package blockchain_api is a MINIMAL, wire-compatible subset of Teranode's
// blockchain service — just enough to subscribe to its notification stream.
//
// Only four things are load-bearing on the wire: the proto package name, the
// service name, the method name, and the field numbers. Everything else here is
// deliberately trimmed:
//
//   * `type` is declared int32 rather than model.NotificationType. A proto enum
//     is a varint, so this is byte-identical and it drops the import of
//     model.proto entirely.
//   * Notification.metadata (field 4) is omitted. Unknown fields are skipped by
//     any conformant parser, so leaving it out costs nothing and keeps this file
//     free of a nested map type we never read.
//   * Empty stands in for google.protobuf.Empty. An empty message serialises to
//     zero bytes whatever its declared type, so this is byte-identical on the
//     wire and drops the well-known-types import.
//   * GetBlockHeaderResponse declares only `height` (field 3). The other
//     fourteen fields are skipped as unknown, which is exactly what we want:
//     the bridge reads the cluster's height, not its headers.
//
// Upstream: teranode/services/blockchain/blockchain_api/blockchain_api.proto
// @ 1cca625 (rpc Subscribe :125, SubscribeRequest :496, Notification :501;
// rpc GetFSMCurrentState :172, GetFSMStateResponse :646, FSMStateType :922;
// rpc GetBestBlockHeader :103, GetBlockHeaderResponse height :3).
// Regenerate with: buf generate  (see buf.gen.yaml)

package blockchain_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FSMStateType mirrors the upstream enum, including its reserved slot, so a
// value the cluster sends is never silently reinterpreted.
type FSMStateType int32

const (
	FSMStateType_IDLE           FSMStateType = 0
	FSMStateType_RUNNING        FSMStateType = 1
	FSMStateType_CATCHINGBLOCKS FSMStateType = 2
)

// Enum value maps for FSMStateType.
var (
	FSMStateType_name = map[int32]string{
		0: "IDLE",
		1: "RUNNING",
		2: "CATCHINGBLOCKS",
	}
	FSMStateType_value = map[string]int32{
		"IDLE":           0,
		"RUNNING":        1,
		"CATCHINGBLOCKS": 2,
	}
)

func (x FSMStateType) Enum() *FSMStateType {
	p := new(FSMStateType)
	*p = x
	return p
}

func (x FSMStateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FSMStateType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_blockchain_api_blockchain_proto_enumTypes[0].Descriptor()
}

func (FSMStateType) Type() protoreflect.EnumType {
	return &file_proto_blockchain_api_blockchain_proto_enumTypes[0]
}

func (x FSMStateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FSMStateType.Descriptor instead.
func (FSMStateType) EnumDescriptor() ([]byte, []int) {
	return file_proto_blockchain_api_blockchain_proto_rawDescGZIP(), []int{0}
}

// Empty is wire-identical to google.protobuf.Empty.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_blockchain_api_blockchain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_api_blockchain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_api_blockchain_proto_rawDescGZIP(), []int{0}
}

type GetFSMStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         FSMStateType           `protobuf:"varint,1,opt,name=state,proto3,enum=blockchain_api.FSMStateType" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFSMStateResponse) Reset() {
	*x = GetFSMStateResponse{}
	mi := &file_proto_blockchain_api_blockchain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFSMStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFSMStateResponse) ProtoMessage() {}

func (x *GetFSMStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_api_blockchain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFSMStateResponse.ProtoReflect.Descriptor instead.
func (*GetFSMStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_api_blockchain_proto_rawDescGZIP(), []int{1}
}

func (x *GetFSMStateResponse) GetState() FSMStateType {
	if x != nil {
		return x.State
	}
	return FSMStateType_IDLE
}

type GetBlockHeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockHeaderResponse) Reset() {
	*x = GetBlockHeaderResponse{}
	mi := &file_proto_blockchain_api_blockchain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockHeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockHeaderResponse) ProtoMessage() {}

func (x *GetBlockHeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_api_blockchain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockHeaderResponse.ProtoReflect.Descriptor instead.
func (*GetBlockHeaderResponse) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_api_blockchain_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlockHeaderResponse) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_blockchain_api_blockchain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_api_blockchain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_api_blockchain_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// NotificationType values we care about, mirroring model.NotificationType:
//
//	1 = Subtree, 2 = Block. (0 PING, 4 FSMState, 5 BlockSubtreesSet,
//	6 PeerFailure, 7 BlockPersisted, 8 BlockMinedUnset.)
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Base_URL      string                 `protobuf:"bytes,3,opt,name=base_URL,json=baseURL,proto3" json:"base_URL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_blockchain_api_blockchain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_api_blockchain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_api_blockchain_proto_rawDescGZIP(), []int{4}
}

func (x *Notification) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Notification) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Notification) GetBase_URL() string {
	if x != nil {
		return x.Base_URL
	}
	return ""
}

var File_proto_blockchain_api_blockchain_proto protoreflect.FileDescriptor

const file_proto_blockchain_api_blockchain_proto_rawDesc = "" +
	"\n" +
	"%proto/blockchain_api/blockchain.proto\x12\x0eblockchain_api\"\a\n" +
	"\x05Empty\"I\n" +
	"\x13GetFSMStateResponse\x122\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1c.blockchain_api.FSMStateTypeR\x05state\"0\n" +
	"\x16GetBlockHeaderResponse\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\"*\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\"Q\n" +
	"\fNotification\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x19\n" +
	"\bbase_URL\x18\x03 \x01(\tR\abaseURL*N\n" +
	"\fFSMStateType\x12\b\n" +
	"\x04IDLE\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\x12\n" +
	"\x0eCATCHINGBLOCKS\x10\x02\"\x04\b\x03\x10\x03*\rLEGACYSYNCING2\x8b\x02\n" +
	"\rBlockchainAPI\x12O\n" +
	"\tSubscribe\x12 .blockchain_api.SubscribeRequest\x1a\x1c.blockchain_api.Notification\"\x000\x01\x12R\n" +
	"\x12GetFSMCurrentState\x12\x15.blockchain_api.Empty\x1a#.blockchain_api.GetFSMStateResponse\"\x00\x12U\n" +
	"\x12GetBestBlockHeader\x12\x15.blockchain_api.Empty\x1a&.blockchain_api.GetBlockHeaderResponse\"\x00BLZJgithub.com/lightwebinc/teranode-bridge/proto/blockchain_api;blockchain_apib\x06proto3"

var (
	file_proto_blockchain_api_blockchain_proto_rawDescOnce sync.Once
	file_proto_blockchain_api_blockchain_proto_rawDescData []byte
)

func file_proto_blockchain_api_blockchain_proto_rawDescGZIP() []byte {
	file_proto_blockchain_api_blockchain_proto_rawDescOnce.Do(func() {
		file_proto_blockchain_api_blockchain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_blockchain_api_blockchain_proto_rawDesc), len(file_proto_blockchain_api_blockchain_proto_rawDesc)))
	})
	return file_proto_blockchain_api_blockchain_proto_rawDescData
}

var file_proto_blockchain_api_blockchain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_blockchain_api_blockchain_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_blockchain_api_blockchain_proto_goTypes = []any{
	(FSMStateType)(0),              // 0: blockchain_api.FSMStateType
	(*Empty)(nil),                  // 1: blockchain_api.Empty
	(*GetFSMStateResponse)(nil),    // 2: blockchain_api.GetFSMStateResponse
	(*GetBlockHeaderResponse)(nil), // 3: blockchain_api.GetBlockHeaderResponse
	(*SubscribeRequest)(nil),       // 4: blockchain_api.SubscribeRequest
	(*Notification)(nil),           // 5: blockchain_api.Notification
}
var file_proto_blockchain_api_blockchain_proto_depIdxs = []int32{
	0, // 0: blockchain_api.GetFSMStateResponse.state:type_name -> blockchain_api.FSMStateType
	4, // 1: blockchain_api.BlockchainAPI.Subscribe:input_type -> blockchain_api.SubscribeRequest
	1, // 2: blockchain_api.BlockchainAPI.GetFSMCurrentState:input_type -> blockchain_api.Empty
	1, // 3: blockchain_api.BlockchainAPI.GetBestBlockHeader:input_type -> blockchain_api.Empty
	5, // 4: blockchain_api.BlockchainAPI.Subscribe:output_type -> blockchain_api.Notification
	2, // 5: blockchain_api.BlockchainAPI.GetFSMCurrentState:output_type -> blockchain_api.GetFSMStateResponse
	3, // 6: blockchain_api.BlockchainAPI.GetBestBlockHeader:output_type -> blockchain_api.GetBlockHeaderResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_blockchain_api_blockchain_proto_init() }
func file_proto_blockchain_api_blockchain_proto_init() {
	if File_proto_blockchain_api_blockchain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_blockchain_api_blockchain_proto_rawDesc), len(file_proto_blockchain_api_blockchain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_blockchain_api_blockchain_proto_goTypes,
		DependencyIndexes: file_proto_blockchain_api_blockchain_proto_depIdxs,
		EnumInfos:         file_proto_blockchain_api_blockchain_proto_enumTypes,
		MessageInfos:      file_proto_blockchain_api_blockchain_proto_msgTypes,
	}.Build()
	File_proto_blockchain_api_blockchain_proto = out.File
	file_proto_blockchain_api_blockchain_proto_goTypes = nil
	file_proto_blockchain_api_blockchain_proto_depIdxs = nil
}
