// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: blockchain.proto

// Package blockchain_api is a MINIMAL, wire-compatible subset of Teranode's
// blockchain service — just enough to subscribe to its notification stream.
//
// Only four things are load-bearing on the wire: the proto package name, the
// service name, the method name, and the field numbers. Everything else here is
// deliberately trimmed:
//
//   * `type` is declared int32 rather than model.NotificationType. A proto enum
//     is a varint, so this is byte-identical and it drops the import of
//     model.proto entirely.
//   * Notification.metadata (field 4) is omitted. Unknown fields are skipped by
//     any conformant parser, so leaving it out costs nothing and keeps this file
//     free of a nested map type we never read.
//
// Upstream: teranode/services/blockchain/blockchain_api/blockchain_api.proto
// @ 1cca625 (rpc Subscribe :125, SubscribeRequest :496, Notification :501).
// Regenerate with: buf generate  (see buf.gen.yaml)

package blockchain_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_blockchain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// NotificationType values we care about, mirroring model.NotificationType:
//
//	1 = Subtree, 2 = Block. (0 PING, 4 FSMState, 5 BlockSubtreesSet,
//	6 PeerFailure, 7 BlockPersisted, 8 BlockMinedUnset.)
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Base_URL      string                 `protobuf:"bytes,3,opt,name=base_URL,json=baseURL,proto3" json:"base_URL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_blockchain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_blockchain_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Notification) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Notification) GetBase_URL() string {
	if x != nil {
		return x.Base_URL
	}
	return ""
}

var File_blockchain_proto protoreflect.FileDescriptor

const file_blockchain_proto_rawDesc = "" +
	"\n" +
	"\x10blockchain.proto\x12\x0eblockchain_api\"*\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\"Q\n" +
	"\fNotification\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x19\n" +
	"\bbase_URL\x18\x03 \x01(\tR\abaseURL2`\n" +
	"\rBlockchainAPI\x12O\n" +
	"\tSubscribe\x12 .blockchain_api.SubscribeRequest\x1a\x1c.blockchain_api.Notification\"\x000\x01BLZJgithub.com/lightwebinc/teranode-bridge/proto/blockchain_api;blockchain_apib\x06proto3"

var (
	file_blockchain_proto_rawDescOnce sync.Once
	file_blockchain_proto_rawDescData []byte
)

func file_blockchain_proto_rawDescGZIP() []byte {
	file_blockchain_proto_rawDescOnce.Do(func() {
		file_blockchain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockchain_proto_rawDesc), len(file_blockchain_proto_rawDesc)))
	})
	return file_blockchain_proto_rawDescData
}

var file_blockchain_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blockchain_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: blockchain_api.SubscribeRequest
	(*Notification)(nil),     // 1: blockchain_api.Notification
}
var file_blockchain_proto_depIdxs = []int32{
	0, // 0: blockchain_api.BlockchainAPI.Subscribe:input_type -> blockchain_api.SubscribeRequest
	1, // 1: blockchain_api.BlockchainAPI.Subscribe:output_type -> blockchain_api.Notification
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blockchain_proto_init() }
func file_blockchain_proto_init() {
	if File_blockchain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockchain_proto_rawDesc), len(file_blockchain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blockchain_proto_goTypes,
		DependencyIndexes: file_blockchain_proto_depIdxs,
		MessageInfos:      file_blockchain_proto_msgTypes,
	}.Build()
	File_blockchain_proto = out.File
	file_blockchain_proto_goTypes = nil
	file_blockchain_proto_depIdxs = nil
}
