// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: proto/blockchain_api/blockchain.proto

// Package blockchain_api is a MINIMAL, wire-compatible subset of Teranode's
// blockchain service — just enough to subscribe to its notification stream.
//
// Only four things are load-bearing on the wire: the proto package name, the
// service name, the method name, and the field numbers. Everything else here is
// deliberately trimmed:
//
//   * `type` is declared int32 rather than model.NotificationType. A proto enum
//     is a varint, so this is byte-identical and it drops the import of
//     model.proto entirely.
//   * Notification.metadata (field 4) is omitted. Unknown fields are skipped by
//     any conformant parser, so leaving it out costs nothing and keeps this file
//     free of a nested map type we never read.
//   * Empty stands in for google.protobuf.Empty. An empty message serialises to
//     zero bytes whatever its declared type, so this is byte-identical on the
//     wire and drops the well-known-types import.
//   * GetBlockHeaderResponse declares only `height` (field 3). The other
//     fourteen fields are skipped as unknown, which is exactly what we want:
//     the bridge reads the cluster's height, not its headers.
//
// Upstream: teranode/services/blockchain/blockchain_api/blockchain_api.proto
// @ 1cca625 (rpc Subscribe :125, SubscribeRequest :496, Notification :501;
// rpc GetFSMCurrentState :172, GetFSMStateResponse :646, FSMStateType :922;
// rpc GetBestBlockHeader :103, GetBlockHeaderResponse height :3).
// Regenerate with: buf generate  (see buf.gen.yaml)

package blockchain_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockchainAPI_Subscribe_FullMethodName          = "/blockchain_api.BlockchainAPI/Subscribe"
	BlockchainAPI_GetFSMCurrentState_FullMethodName = "/blockchain_api.BlockchainAPI/GetFSMCurrentState"
	BlockchainAPI_GetBestBlockHeader_FullMethodName = "/blockchain_api.BlockchainAPI/GetBestBlockHeader"
)

// BlockchainAPIClient is the client API for BlockchainAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockchainAPIClient interface {
	// Subscribe streams notifications as the node accepts subtrees and blocks.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error)
	// GetFSMCurrentState reports whether the cluster is RUNNING, IDLE or catching
	// up. The bridge announces and submits identically in every state, so without
	// this reading "the announce succeeded but nothing happened" has no visible
	// cause. Teranode's own services treat this as a health dependency
	// (services/blockchain/fsm.go CheckFSM).
	GetFSMCurrentState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetFSMStateResponse, error)
	// GetBestBlockHeader gives the cluster's tip height, which is what turns a
	// flat announce counter into "the cluster is behind" or "the cluster is fine".
	GetBestBlockHeader(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetBlockHeaderResponse, error)
}

type blockchainAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockchainAPIClient(cc grpc.ClientConnInterface) BlockchainAPIClient {
	return &blockchainAPIClient{cc}
}

func (c *blockchainAPIClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlockchainAPI_ServiceDesc.Streams[0], BlockchainAPI_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Notification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockchainAPI_SubscribeClient = grpc.ServerStreamingClient[Notification]

func (c *blockchainAPIClient) GetFSMCurrentState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetFSMStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFSMStateResponse)
	err := c.cc.Invoke(ctx, BlockchainAPI_GetFSMCurrentState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainAPIClient) GetBestBlockHeader(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetBlockHeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockHeaderResponse)
	err := c.cc.Invoke(ctx, BlockchainAPI_GetBestBlockHeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainAPIServer is the server API for BlockchainAPI service.
// All implementations must embed UnimplementedBlockchainAPIServer
// for forward compatibility.
type BlockchainAPIServer interface {
	// Subscribe streams notifications as the node accepts subtrees and blocks.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Notification]) error
	// GetFSMCurrentState reports whether the cluster is RUNNING, IDLE or catching
	// up. The bridge announces and submits identically in every state, so without
	// this reading "the announce succeeded but nothing happened" has no visible
	// cause. Teranode's own services treat this as a health dependency
	// (services/blockchain/fsm.go CheckFSM).
	GetFSMCurrentState(context.Context, *Empty) (*GetFSMStateResponse, error)
	// GetBestBlockHeader gives the cluster's tip height, which is what turns a
	// flat announce counter into "the cluster is behind" or "the cluster is fine".
	GetBestBlockHeader(context.Context, *Empty) (*GetBlockHeaderResponse, error)
	mustEmbedUnimplementedBlockchainAPIServer()
}

// UnimplementedBlockchainAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockchainAPIServer struct{}

func (UnimplementedBlockchainAPIServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Notification]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedBlockchainAPIServer) GetFSMCurrentState(context.Context, *Empty) (*GetFSMStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFSMCurrentState not implemented")
}
func (UnimplementedBlockchainAPIServer) GetBestBlockHeader(context.Context, *Empty) (*GetBlockHeaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBestBlockHeader not implemented")
}
func (UnimplementedBlockchainAPIServer) mustEmbedUnimplementedBlockchainAPIServer() {}
func (UnimplementedBlockchainAPIServer) testEmbeddedByValue()                       {}

// UnsafeBlockchainAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockchainAPIServer will
// result in compilation errors.
type UnsafeBlockchainAPIServer interface {
	mustEmbedUnimplementedBlockchainAPIServer()
}

func RegisterBlockchainAPIServer(s grpc.ServiceRegistrar, srv BlockchainAPIServer) {
	// If the following call panics, it indicates UnimplementedBlockchainAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockchainAPI_ServiceDesc, srv)
}

func _BlockchainAPI_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockchainAPIServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Notification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockchainAPI_SubscribeServer = grpc.ServerStreamingServer[Notification]

func _BlockchainAPI_GetFSMCurrentState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainAPIServer).GetFSMCurrentState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainAPI_GetFSMCurrentState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainAPIServer).GetFSMCurrentState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainAPI_GetBestBlockHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainAPIServer).GetBestBlockHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainAPI_GetBestBlockHeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainAPIServer).GetBestBlockHeader(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockchainAPI_ServiceDesc is the grpc.ServiceDesc for BlockchainAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockchainAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain_api.BlockchainAPI",
	HandlerType: (*BlockchainAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFSMCurrentState",
			Handler:    _BlockchainAPI_GetFSMCurrentState_Handler,
		},
		{
			MethodName: "GetBestBlockHeader",
			Handler:    _BlockchainAPI_GetBestBlockHeader_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _BlockchainAPI_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/blockchain_api/blockchain.proto",
}
