// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: blockchain.proto

// Package blockchain_api is a MINIMAL, wire-compatible subset of Teranode's
// blockchain service — just enough to subscribe to its notification stream.
//
// Only four things are load-bearing on the wire: the proto package name, the
// service name, the method name, and the field numbers. Everything else here is
// deliberately trimmed:
//
//   * `type` is declared int32 rather than model.NotificationType. A proto enum
//     is a varint, so this is byte-identical and it drops the import of
//     model.proto entirely.
//   * Notification.metadata (field 4) is omitted. Unknown fields are skipped by
//     any conformant parser, so leaving it out costs nothing and keeps this file
//     free of a nested map type we never read.
//
// Upstream: teranode/services/blockchain/blockchain_api/blockchain_api.proto
// @ 1cca625 (rpc Subscribe :125, SubscribeRequest :496, Notification :501).
// Regenerate with: buf generate  (see buf.gen.yaml)

package blockchain_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockchainAPI_Subscribe_FullMethodName = "/blockchain_api.BlockchainAPI/Subscribe"
)

// BlockchainAPIClient is the client API for BlockchainAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockchainAPIClient interface {
	// Subscribe streams notifications as the node accepts subtrees and blocks.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error)
}

type blockchainAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockchainAPIClient(cc grpc.ClientConnInterface) BlockchainAPIClient {
	return &blockchainAPIClient{cc}
}

func (c *blockchainAPIClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlockchainAPI_ServiceDesc.Streams[0], BlockchainAPI_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Notification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockchainAPI_SubscribeClient = grpc.ServerStreamingClient[Notification]

// BlockchainAPIServer is the server API for BlockchainAPI service.
// All implementations must embed UnimplementedBlockchainAPIServer
// for forward compatibility.
type BlockchainAPIServer interface {
	// Subscribe streams notifications as the node accepts subtrees and blocks.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Notification]) error
	mustEmbedUnimplementedBlockchainAPIServer()
}

// UnimplementedBlockchainAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockchainAPIServer struct{}

func (UnimplementedBlockchainAPIServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Notification]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedBlockchainAPIServer) mustEmbedUnimplementedBlockchainAPIServer() {}
func (UnimplementedBlockchainAPIServer) testEmbeddedByValue()                       {}

// UnsafeBlockchainAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockchainAPIServer will
// result in compilation errors.
type UnsafeBlockchainAPIServer interface {
	mustEmbedUnimplementedBlockchainAPIServer()
}

func RegisterBlockchainAPIServer(s grpc.ServiceRegistrar, srv BlockchainAPIServer) {
	// If the following call panics, it indicates UnimplementedBlockchainAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockchainAPI_ServiceDesc, srv)
}

func _BlockchainAPI_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockchainAPIServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Notification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockchainAPI_SubscribeServer = grpc.ServerStreamingServer[Notification]

// BlockchainAPI_ServiceDesc is the grpc.ServiceDesc for BlockchainAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockchainAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain_api.BlockchainAPI",
	HandlerType: (*BlockchainAPIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _BlockchainAPI_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blockchain.proto",
}
