name: Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  release:
    permissions:
      contents: write
    uses: lightwebinc/ci/.github/workflows/gh-release.yml@3f438e60ade351107a3d1601955ebbf34de8caf1 # v0.1.0
