name: Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  release:
    permissions:
      contents: write
    uses: lightwebinc/ci/.github/workflows/gh-release.yml@3c61864e6d822d16119858e525129ea5c400d4d7 # v0.4.0
