name: Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  release:
    permissions:
      contents: write
    uses: lightwebinc/ci/.github/workflows/gh-release.yml@192a5b5169fd635e191104c14631525bbcd5ec60 # v0.3.0
